### PR TITLE
Leftovers from some previous version?

### PR DESCRIPTION
**Pull request by thaewrapt**
Removed the unnecessary/unused global variable. Perl habits are strong :)

### CODE REVIEW

**Comment by berestovskyy** [comment]
Hey,
The variable is needed there indeed to introduce a misalignment for the following `array`.

Without this global integer, the `array` will be the first global variable in `.bss`, hence the first element of the `array` will be aligned to the 64 bytes.

**Comment by thaewrapt** [comment]
Well, I've suspected that it was here for a reason, though with my clang-7.0.1 (-O3) the alignment/non-alignment of forementioned arrays is still constant between both versions (with and without preciding "int _;").

**Comment by thaewrapt** [comment]
So, for `array` it's only "is not aligned" for all the four elements of it, of course.

**Comment by berestovskyy** [comment]
Yeah, it depends. In my case it was necessary to break the alignment. Your mileage may vary.

**Comment by thaewrapt** [comment]
Yep, I've discovered already that we couldn't be guaranteed [implementation independently] the needed memory shift in C++ not doing something alike.

**Pull request closed without merging**
